[package]
name = "orbtk-example"
version = "0.1.0"
authors = ["707 <707472783@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
orbtk = "0.3.1-alpha1"