[package]
name = "myice"
version = "0.1.0"
authors = ["707 <707472783@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = "0.1.0-beta"